sudo: required

language: python
python:
  - 3.6

services:
  - docker

before_install:
  - docker build --rm -t ughjobs/ughjobs .
  - docker run -d --name ughjobs ughjobs/ughjobs
  - docker run ughjobs/ughjobs ./manage.py test

script:
  - ./manage.py test
