sudo: required
services:
  - docker
before_install:
  - docker build --rm -t ughjobs/jobshop -f Dockerfile .
  - docker run -p 5000:5000 --rm -d --name jobshop ughjobs/jobshop
  - docker build --rm -t ughjobs/webapp -f WebApp/Dockerfile .
  - docker run -p 4200:4200 --rm -d --name webapp ughjobs/webapp

matrix:
  include:
  - language: python
    python: 3.6
    install:
      - pip install -r requirements.txt
      - pip install -r test-requirements.txt
    script:
      - python tests/test_endpoints.py

  - language: node_js
    install:
      - npm install -g @angular/cli
    before_script:
      - cd WebApp/
    script:
      - ng test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push ughjobs/jobshop;
    docker push ughjobs/webapp;
    fi
