sudo: required

language: python
python:
  - 3.6

services:
  - docker

before_install:
  - docker build --rm -t ughjobs/ughjobs .
  - docker run -d --name ughjobs ughjobs/ughjobs

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - pytest

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push ughjobs/ughjobs;
    fi
