# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Application(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, job_id=None):
        """
        Application - a model defined in Swagger

        :param id: The id of this Application.
        :type id: int
        :param job_id: The job_id of this Application.
        :type job_id: int
        """
        self.swagger_types = {
            'id': int,
            'job_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'job_id': 'job_id'
        }

        self._id = id
        self._job_id = job_id

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Application of this Application.
        :rtype: Application
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self):
        """
        Gets the id of this Application.

        :return: The id of this Application.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Application.

        :param id: The id of this Application.
        :type id: int
        """

        self._id = id

    @property
    def job_id(self):
        """
        Gets the job_id of this Application.

        :return: The job_id of this Application.
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """
        Sets the job_id of this Application.

        :param job_id: The job_id of this Application.
        :type job_id: int
        """

        self._job_id = job_id

