swagger: '2.0'
info:
  description: Ten dokument stanowi specyfkację JSON REST API dla aplikacji UGHJobs.
  version: 1.0.0
  title: UGHJobs API
basePath: /api
tags:
  - name: job
    description: Wszystkie operacje na wystawionych ofertach pracy.
  - name: application
    description: Wszystkie operacje na zgłoszeniach do ofert pracy.
  - name: user
    description: Wszystkie operacje na użytkownikach.
schemes:
  - http
paths:
  /users:
    get:
      summary: Wyświetlenie wszystkich użytkowników
      tags:
        - user
      responses:
        '200':
          description: OK
    post:
      summary: Dodanie nowego użytkownika
      tags:
        - user
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: Użytkownik utworzony.
  '/users/{id}':
    parameters:
      - name: id
        in: path
        description: Identyfikator użytkownika.
        type: integer
        required: true
    get:
      summary: Wyświetlenie pojedynczego użytkownika
      tags:
        - user
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
    delete:
      summary: Usunięcie użytkownika.
      tags:
        - user
      responses:
        '200':
          description: Usunięto.
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      email:
        type: string
        format: email
      password:
        type: string
        minLength: 8
        maxLength: 32
      name:
        type: string
      surname:
        type: string
      account:
        type: string
        enum:
          - admin
          - company
          - employee
    xml:
      name: User
  Job:
    type: object
  Application:
    type: object
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
