swagger: '2.0'
info:
  description: Ten dokument stanowi specyfkację JSON REST API dla aplikacji UGHJobs.
  version: 1.0.0
  title: UGHJobs API
basePath: /api
tags:
  - name: job
    description: Wszystkie operacje na wystawionych ofertach pracy.
  - name: application
    description: Wszystkie operacje na zgłoszeniach do ofert pracy.
  - name: user
    description: Wszystkie operacje na użytkownikach.
schemes:
  - http
paths:
  /users:
    get:
      summary: Wyświetlenie wszystkich użytkowników
      tags:
        - user
      responses:
        '200':
          description: OK
    post:
      summary: Dodanie nowego użytkownika
      tags:
        - user
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: Użytkownik utworzony.
  '/users/{id}':
    parameters:
      - name: id
        in: path
        description: Identyfikator użytkownika.
        type: integer
        required: true
    get:
      summary: Wyświetlenie pojedynczego użytkownika
      tags:
        - user
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
    delete:
      summary: Usunięcie użytkownika.
      tags:
        - user
      responses:
        '200':
          description: Usunięto.
  /jobs:
    get:
      summary: Wyświetlenie wszystkich ofert pracy
      tags:
        - job
      responses:
        '200':
          description: OK
    post:
      summary: Dodanie nowego ogłoszenia
      tags:
        - job
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Job'
      responses:
        '201':
          description: Użytkownik utworzony.
  '/jobs/{id}':
    parameters:
      - name: id
        in: path
        description: Identyfikator oferty pracy.
        type: integer
        required: true
    get:
      summary: Wyświetlenie pojedynczej oferty
      tags:
        - job
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Job'
    delete:
      summary: Usunięcie oferty.
      tags:
        - job
      responses:
        '200':
          description: Usunięto.
  '/jobs/{id}/apply':
    parameters:
      - name: id
        in: path
        description: Identyfikator oferty pracy.
        type: integer
        required: true
    post:
      summary: Dodanie nowego zgłoszenia do oferty
      tags:
        - application
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Application'
      responses:
        '201':
          description: Dodano zgłoszenie
  /applications:
    get:
      summary: Wyświetlenie wszystkich zgłoszeń
      tags:
        - application
      responses:
        '200':
          description: OK
  '/applications/{id}':
    parameters:
      - name: id
        in: path
        description: Identyfikator zgłoszenia o prace
        type: integer
        required: true
    get:
      summary: Wyświetlenie pojedynczego zgłoszenia
      tags:
        - application
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Application'
    delete:
      summary: Usunięcie zgłoszenia.
      tags:
        - application
      responses:
        '200':
          description: Usunięto.
  /companies:
    get:
      summary: Wyświetlenie wszystkich firm
      tags:
        - companies
      responses:
        '200':
          description: OK
    post:
      summary: Dodanie nowej firmy
      tags:
        - companies
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Company'
      responses:
        '201':
          description: Firma utworzona.
  '/companies/{id}':
    parameters:
      - name: id
        in: path
        description: Identyfikator firmy
        type: integer
        required: true
    get:
      summary: Wyświetlenie pojedynczej firmy
      tags:
        - companies
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Company'
    delete:
      summary: Usunięcie firmy.
      tags:
        - companies
      responses:
        '200':
          description: Usunięto.
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      email:
        type: string
        format: email
      password:
        type: string
        minLength: 8
        maxLength: 32
      name:
        type: string
      surname:
        type: string
      account:
        type: string
        enum:
          - admin
          - company
          - employee
    xml:
      name: User
  Job:
    type: object
    properties:
      id:
        type: integer
        format: int64
      company:
        type: integer
        format: int64
      expire:
        type: string
        format: date
      content:
        type: string
        format: byte
  Application:
    type: object
    properties:
      id:
        type: integer
        format: int64
      job_id:
        type: integer
        format: int64
  Company:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        minLength: 3
        maxLength: 32
      tax_number:
        type: integer
        format: int64
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
