swagger: "2.0"
info:
  description: "Ladowanie statycznego kontentu"
  version: "1.0.0"
  title: "Static content"
basePath: "/"
schemes:
- "http"
paths:
  /:
    get:
      tags:
      - "app"
      summary: "Index.html"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "ughjobs.controllers.static_controller"
      operationId: "index_get"
  /{path}:
    get:
      tags:
      - "app"
      summary: "Statyczny kontent"
      parameters:
      - in: "path"
        required: true
        name: "path"
        type: "string"
        format: "path"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "ughjobs.controllers.static_controller"
      operationId: "app_get"